<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'application\\factory' => '/src/Factory.php',
                'library\\dataaccess\\entityidentifier' => '/src/Library/DataAccess/EntityIdentifier.php',
                'library\\dataaccess\\identifier' => '/src/Library/DataAccess/Identifier.php',
                'library\\dataaccess\\identifiercollection' => '/src/Library/DataAccess/IdentifierCollection.php',
                'library\\dataaccess\\uuid' => '/src/Library/DataAccess/UUID.php',
                'library\\exceptions\\applicationexception' => '/src/Library/Exceptions/ApplicationException.php',
                'library\\exceptions\\duplicateentityexception' => '/src/Library/Exceptions/DuplicateEntityException.php',
                'library\\exceptions\\foreignkeyconstraintviolationexception' => '/src/Library/Exceptions/ForeignKeyConstraintViolationException.php',
                'library\\exceptions\\invalidargumentexception' => '/src/Library/Exceptions/InvalidArgumentException.php',
                'riskalyzedomainobjects\\library\\dataaccess\\adapters\\adapter' => '/src/Library/DataAccess/Adapters/Adapter.php',
                'riskalyzedomainobjects\\library\\dataaccess\\adapters\\mysqliadapter' => '/src/Library/DataAccess/Adapters/MysqliAdapter.php',
                'riskalyzedomainobjects\\library\\scalarobjects\\booleanvalueobject' => '/src/Library/ScalarObjects/BooleanValueObject.php',
                'riskalyzedomainobjects\\library\\scalarobjects\\integervalueobject' => '/src/Library/ScalarObjects/IntegerValueObject.php',
                'riskalyzedomainobjects\\library\\scalarobjects\\numericvalueobject' => '/src/Library/ScalarObjects/NumericValueObject.php',
                'riskalyzedomainobjects\\library\\scalarobjects\\stringvalueobject' => '/src/Library/ScalarObjects/StringValueObject.php',
                'user\\user' => '/src/User/User.php',
                'user\\userarrayloader' => '/src/User/UserArrayLoader.php',
                'user\\userid' => '/src/User/UserId.php',
                'user\\userloader' => '/src/User/UserLoader.php',
                'user\\usermapper' => '/src/User/UserMapper.php',
                'user\\usermysqliloader' => '/src/User/UserMysqliLoader.php',
                'user\\username' => '/src/User/UserName.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
